### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by wSedlacek** [shackley/swift-blade#2]
I am pretty new to swift but I am running into issues getting this building on linux.
It appears that `OSAllocatedUnfairLock` from `import os` is an Apple only API.

https://github.com/shackley/swift-blade/blob/3a37bd49cd297d8aa5d4451207c1d029389e20d8/Sources/Blade/Lazy.swift#L22C23-L22C44e

Is there another way to solve the problem `Lazy` is doing without `OSAllocatedUnfairLock`?

Some members of the Vapor discord had suggested using `NIOLock` or `NSLock` on Linux. There was some great conversation about the preformance differences between OSUnfairLock and these other solutions. 

The converstation can be found starting from here:
https://discord.com/channels/431917998102675485/499822537027616768/1186767808193888368

**Comment by shackley** [comment]
Hi @wSedlacek,

Thanks for the report!

I replaced `OSAllocatedUnfairLock` usage with an `UnfairLock` class that is backed by `os_unfair_lock_s` on Darwin platforms and `pthread_mutex_t` on Linux. https://github.com/shackley/swift-blade/commit/372800eb6628e78b09d14bc15a5d9d2c4f439b9b.

This change has been included in the [0.1.3](https://github.com/shackley/swift-blade/releases/tag/0.1.3) release.
