### ISSUE TITLE
Error: Runtime support for parameterized protocol types is only available in iOS 16.0.0 or newer

### ISSUE THREAD

**Issue by ArtiomKha** [shackley/swift-blade#4]
I'm getting following errors when using 0.1.4 version. My project minimal deployment target is iOS 16
On version 0.1.2 everyting is fine.
![Снимок экрана 2024-07-29 в 00 22 10](https://github.com/user-attachments/assets/0dc3714f-9e81-4350-9e42-984c907a224e)

**Comment by shackley** [comment]
Ah oops, I forgot parameterized protocol types require iOS 16.

I just fixed the min iOS version in the [0.1.5](https://github.com/shackley/swift-blade/releases/tag/0.1.5) release.
